export const NEW_SUBTITLE_FILE = 'NEW_SUBTITLE_FILE';
export const LOAD_SUBTITLE_FILE = 'LOAD_SUBTITLE_FILE';
export const SAVE_SUBTITLE_FILE = 'SAVE_SUBTITLE_FILE';
export const LOAD_VIDEO = 'LOAD_VIDEO';
